### ISSUE TITLE
Support two more arguments

### ISSUE THREAD

**Issue by linsyking** [BoYanZh/JI-Auth#2]
Adding those arguments:
`--username`
`--password`
`getpass` has some problems when reading stdin.

**Comment by linsyking** [comment]
Or maybe use input `instead` of `getpass`?

**Comment by linsyking** [comment]
Or can you simply replace `getpass` with `input`?

**Comment by linsyking** [comment]
The problem with `getpass` is that it reads input from TTY.

**Comment by BoYanZh** [comment]
I think since you need to input the captcha code each time, you show run the tool manually instead of using redirection.

**Comment by linsyking** [comment]
> I think since you need to input the captcha code each time, you show run the tool manually instead of using redirection.

I use `child_process` to interact with the python script.

You can see my VSCode JOJ Tools, https://github.com/linsyking/vscode-joj-tools, I integrate JOJ tools.

**Comment by BoYanZh** [comment]
It seems that you use a self-made `joj-auth` for getting JOJ_SID? Anyway, could you please create a PR for that?

**Comment by linsyking** [comment]
> It seems that you use a self-made `joj-auth` for getting JOJ_SID? Anyway, could you please create a PR for that?

right away

**Comment by linsyking** [comment]
btw, i wonder if there is a jaccount_cli for nodejs... :sob:

**Comment by BoYanZh** [comment]
You can just translate it to nodejs https://github.com/tc-imba/python-jaccount-cli/blob/master/jaccount_cli/asyncio.py
