### ISSUE TITLE
Bug in python-jaccount-cli

### ISSUE THREAD

**Issue by linsyking** [BoYanZh/JI-Auth#7]
https://github.com/tc-imba/python-jaccount-cli/pull/2

That package cannot work anymore, and I cannot contact with the author. Shall we create a new package instead?

**Comment by BoYanZh** [comment]
Okay. You can fork that package and I will update the deps in this package.

**Comment by linsyking** [comment]
Created `jaccount_auth`.

You might need to change `requirements.txt` and `login.py`

**Comment by BoYanZh** [comment]
Can you raise a PR for the changes and test it? I can not reach a PC and test it recently.

**Comment by linsyking** [comment]
> Can you raise a PR for the changes and test it? I can not reach a PC and test it recently.

I have submitted one, please check it out :)

**Comment by linsyking** [comment]
May you publish this to pypi? Since the new semester is coming, we hope that new students can use joj tools. Thanks!

**Comment by BoYanZh** [comment]
Done.

**Comment by linsyking** [comment]
> Done.

Great! Thanks
