### ISSUE TITLE
Change of website

### ISSUE THREAD

**Issue by Hydraallen** [BoYanZh/JI-Auth#8]
The website of JI has been changed from `https://umjicanvas.com` to `https://www.jicanvas.com`. 

The website in this package may also need to be updated.

**Comment by BoYanZh** [comment]
Sure! You are welcomed to raise a PR for that.

**Comment by Hydraallen** [comment]
I have raise a [PR](https://github.com/BoYanZh/JI-Auth/pull/9) for that. Can you have a look?
